[project]
name = "math-assistant-mcp-server"
version = "1.0.0"
description = "Math Assistant MCP Server using FastMCP and UV"
requires-python = ">=3.10"
dependencies = [
    "fastmcp>=0.4.0",
]

[tool.uv]
dev-dependencies = []
